<a href="https://colab.research.google.com/github/lucasbarrosrocha/projeto_IA/blob/master/TRABALHO%2BIA_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Lista de atividades

- [x] Introduzir o trabalho (tema, componentes)
- [x] Detalhar fonte dos dados
- [x] Explicar quatitativamente os dados
- [x] Expor as variáveis (features)
- [x] Remover dados invalidos
- [x] Dividir os dados em treino e teste
- [x] Expor algoritmos usados no trabalho
- [x] Treinar com as variáveis puras
- [x] Avaliar resultados
- [x] Ajustar as variáveis
- [x] Treinar novamente
- [x] Avaliar novos resultados
- [x] Ajustar paramentros dos algoritmos 
- [x] Avaliar novos resultados 2
- [x] Testar com df de teste
- [ ] Avaliar resultados finais 
- [ ] Criar Slide
- [x] (optional) Fazer análise de features importantes para o modelo
- [ ] (optional) Ajustar features com valor qualitativo


# Apresentação parcial

## Equipe:

* Lucas Barros</br>  
* Luiz Ricardo</br>  
* Maiana Jardelle</br>  
* Pedro Henrique</br>  
* Volney Gomes

## Usando algoritmos de aprendizagem de máquina para prever resultados de partida de futebol


In [0]:
import pandas as pd
import numpy as np

### Importando dados

In [42]:
# df = pd.read_csv('/home/lucas/Documentos/soccer/Total.csv', low_memory=False)
# print(*df.columns, sep='\n')
df = pd.read_csv('https://raw.githubusercontent.com/lucasbarrosrocha/projeto_IA/master/dataframe/resume%20.csv')
df = df.drop(columns=['Unnamed: 0'])

def size_dataframe(df):
    resume = pd.DataFrame()
    resume = pd.DataFrame(columns=['Linhas','Colunas'])
    resume.loc['Dados'] = df.shape[0], df.shape[1]
    # resume = pd.DataFrame(columns=['Linhas'])
    # resume.loc['Dados'] = df.shape[0]
    return resume

size_dataframe(df)

Linhas Colunas
Dados  37540      21

## Dados disponíveis
**9** Campeonatos:
* **Brazil A** - Brasil (Série A)
* **Brazil B** - Brasil (Série B)
* **English A** - Inglaterra (Premier League)
* **Spain A** - Espanha (La Liga)
* **Germany A** - Alemanha (Bundesliga)
* **Italy A** - Itália (Serie A)
* **France A** - França (Ligue 1)
* **Portugal A** - Portugal (Primeira Liga)
* **Netherlands A** - Holanda (Eredivisie)

**Sobre os dados:** o dados foram colhidos do site www.betexplorer.com.br, contendo informações do time de futebol, cotação da casas de apostas, resultado do jogo, data e hora, dentre outros.

<br/>

<img src='data.png' />

<br/>

É importante obserar que alguns campeonatos tem menos jogos que o outro. Isso se deve ao fato do campeonato ter menos times na competição.
O campeonato português, particularmente, passou de 16 para 18 times a partir de 2014, o que pode ser observado no aumento do número de jogos.


### Constantes referentes as colunas do data frame

In [0]:
GAME_RESULT = 'm.res.1x2'
BTS_RESULT = 'm.res.bts'

YEAR = 'm.ss.yi'
CHAMPIONSHIP = 'm.ss.ch.nm'
HOME_TEAM = 'm.th'
AWAY_TEAM = 'm.ta'

ML_AVERAGE_ODD_FAVORITE = 'm.odds.f.1x2.f.v.med'
ML_AVERAGE_ODD_MIDDLE = 'm.odds.f.1x2.m.v.med'
ML_AVERAGE_ODD_UNDERDOG = 'm.odds.f.1x2.u.v.med'
ML_OPTION_FAVORITE = 'm.odds.f.1x2.f.c'
ML_OPTION_MIDDLE = 'm.odds.f.1x2.m.c'
ML_OPTION_UNDERDOG = 'm.odds.f.1x2.u.c'
BTS_AVERAGE_ODD_FAVORTIE = 'm.odds.f.bts.f.v.med'
BTS_AVERAGE_ODD_UNDERDOG = 'm.odds.f.bts.u.v.med'
BTS_OPTION_FAVORITE = 'm.odds.f.bts.f.c'
BTS_OPTION_UNDERDOG = 'm.odds.f.bts.u.c'

FAVORITE_ODDS = 'm.odds.f.1x2.f.c'
FAVORITE = 'm.odds.f.1x2.f.v.avg'


In [43]:
df

m.ss.yi m.ss.ch.nm  ... m.odds.s.bts.y.t.med m.odds.s.bts.n.t.med
0         2007   Brazil B  ...                  NaN                  NaN
1         2007   Brazil B  ...                  NaN                  NaN
2         2007   Brazil B  ...                  NaN                  NaN
3         2007   Brazil B  ...                  NaN                  NaN
4         2007   Brazil B  ...                  NaN                  NaN
...        ...        ...  ...                  ...                  ...
37535     2017  Germany A  ...               0.6154               0.3846
37536     2017  Germany A  ...               0.5202               0.4798
37537     2017  Germany A  ...               0.5571               0.4429
37538     2017  Germany A  ...               0.6104               0.3896
37539     2017  Germany A  ...               0.5270               0.4730

[37540 rows x 21 columns]

### Funções de uso geral

In [0]:
def formater_porcent(value):
    return( "%.2f" % (float(value) * 100))

### Verificando tamanho do data frame


In [6]:
print(len(df))

37540


### Removendo linhas que tem resultado do jogo vazio

In [7]:
df = df[df[GAME_RESULT].notnull()]
print(len(df))

37538


### Removendo linhas que tem odds do favorito vazio

In [8]:
df = df[df[FAVORITE_ODDS].notnull()]
print(len(df))

36388


In [9]:
df = df[df[ML_AVERAGE_ODD_FAVORITE].notnull()]
df = df[df[ML_AVERAGE_ODD_MIDDLE].notnull()]
df = df[df[ML_AVERAGE_ODD_UNDERDOG].notnull()]
df = df[df[ML_OPTION_FAVORITE].notnull()]
df = df[df[ML_OPTION_MIDDLE].notnull()]
df = df[df[ML_OPTION_UNDERDOG].notnull()]
df = df[df[BTS_AVERAGE_ODD_FAVORTIE].notnull()]
df = df[df[BTS_AVERAGE_ODD_UNDERDOG].notnull()]
df = df[df[BTS_OPTION_FAVORITE].notnull()]
df = df[df[BTS_OPTION_UNDERDOG].notnull()]

print(len(df))

16749


## Divisão do Datafarme - Treino/Teste

In [10]:
split_year = 2015   

df_train = df[(df[YEAR] <= split_year)]
df_test = df[(df[YEAR] > split_year)]   

print('tamanho df treino: ' + str(len(df_train)))
print('tamanho df teste: ' + str(len(df_test)))
print(len(df_train)+len(df_test) == len(df))

tamanho df treino: 10665
tamanho df teste: 6084
True


## Escolha dos algoritmos de aprendizagem de máquina

* AdaBoost  
* RandomForest  
* GradientBoosting  

## Importando algoritmos de aprendizagem de máquina

In [0]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
# from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import GridSearchCV

ada_clf = AdaBoostClassifier()
rf_clf = RandomForestClassifier()
grad_clf = GradientBoostingClassifier()

# from sklearn.grid_search import GridSearchCV

### Funções para predição.

In [0]:
def prediction_features(clf,target, dataFrame, features):
    param_grid = {}
    grid= GridSearchCV(clf, param_grid=param_grid, verbose=1, cv=5)

    grid.fit(dataFrame[features],dataFrame[target])
    clf.fit(dataFrame[features],dataFrame[target])

    # print(grid.grid_scores_)
    print(grid.best_score_)
    print('features importantes')
    print(clf.feature_importances_)


## Treinando algoritmos com features não tratadas


In [0]:
feature_train = [ ML_AVERAGE_ODD_FAVORITE,
ML_AVERAGE_ODD_MIDDLE,
ML_AVERAGE_ODD_UNDERDOG,
BTS_AVERAGE_ODD_FAVORTIE,
BTS_AVERAGE_ODD_UNDERDOG ]

### * Treinando Adaboost

In [14]:
prediction_features(ada_clf, GAME_RESULT, df_train, feature_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    3.3s finished


0.46169714017815283
features importantes
[0.26 0.18 0.22 0.18 0.16]


### * Treinando RandomForest

In [15]:
prediction_features(rf_clf, GAME_RESULT, df_train, feature_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/

0.38406000937646506
features importantes
[0.21576403 0.20647098 0.22007883 0.17394355 0.18374262]


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


### * Treinando GradientBoosting

In [16]:
prediction_features(grad_clf, GAME_RESULT, df_train, feature_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    7.0s finished


0.4556024378809189
features importantes
[0.44260802 0.16200666 0.18329197 0.09282818 0.11926517]


## Novas features criadas


In [0]:
ML_REAL_PROB_HOME = 'm.odds.s.1x2.h.t.med'
ML_REAL_PROB_DRAW = 'm.odds.s.1x2.d.t.med'
ML_REAL_PROB_AWAY = 'm.odds.s.1x2.a.t.med'
BTS_REAL_PROB_FAVORITE = 'm.odds.s.bts.y.t.med'
BTS_REAL_PROB_UNDERDOG = 'm.odds.s.bts.n.t.med'

In [45]:
df[[HOME_TEAM, AWAY_TEAM, ML_REAL_PROB_HOME,ML_REAL_PROB_DRAW,ML_REAL_PROB_AWAY]]

m.th  ... m.odds.s.1x2.a.t.med
0               Avai  ...                  NaN
1              Ceara  ...                  NaN
2                CRB  ...                  NaN
3               Gama  ...                  NaN
4            Marilia  ...                  NaN
...              ...  ...                  ...
37535     Hoffenheim  ...               0.2233
37536          Mainz  ...               0.2222
37537        Schalke  ...               0.3773
37538      Wolfsburg  ...               0.4994
37539  Bayern Munich  ...               0.0902

[37540 rows x 5 columns]

## Treinando algoritmos com features não tratadas


In [0]:
feature_train_news = [ ML_AVERAGE_ODD_FAVORITE,
ML_AVERAGE_ODD_MIDDLE,
ML_AVERAGE_ODD_UNDERDOG,
BTS_AVERAGE_ODD_FAVORTIE,
BTS_AVERAGE_ODD_UNDERDOG,
ML_REAL_PROB_HOME,
ML_REAL_PROB_DRAW,
ML_REAL_PROB_AWAY,
BTS_REAL_PROB_FAVORITE,
BTS_REAL_PROB_UNDERDOG]

### * Treinando Adaboost

In [19]:
prediction_features(ada_clf, GAME_RESULT, df_train, feature_train_news)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    4.4s finished


0.5241443975621191
features importantes
[0.08 0.08 0.02 0.04 0.04 0.26 0.16 0.18 0.1  0.04]


### * Treinando RandomForest

In [20]:
prediction_features(rf_clf, GAME_RESULT, df_train, feature_train_news)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.2s finished


0.4608532583216127
features importantes
[0.08479161 0.0751553  0.08444001 0.07408939 0.06879575 0.1423311
 0.12631348 0.16131328 0.09010462 0.09266545]


### * Treinando GradientBoosting

In [21]:
prediction_features(grad_clf, GAME_RESULT, df_train, feature_train_news)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   10.8s finished


0.5290201593999062
features importantes
[0.04113103 0.03096399 0.04618918 0.0229219  0.02154279 0.48214817
 0.10316009 0.1943885  0.03115908 0.02639528]


## Treinando algoritmos apenas com features novas


In [0]:
feature_train_news_features = [ 
ML_REAL_PROB_HOME,
ML_REAL_PROB_DRAW,
ML_REAL_PROB_AWAY]

### * Treinando Adaboost

In [23]:
prediction_features(ada_clf, GAME_RESULT, df_train, feature_train_news_features)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    3.5s finished


0.5294889826535396
features importantes
[0.28 0.32 0.4 ]


### * Treinando RandomForest

In [24]:
prediction_features(rf_clf, GAME_RESULT, df_train, feature_train_news_features)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.7s finished


0.4556024378809189
features importantes
[0.34644023 0.30972228 0.34383749]


### * Treinando GradientBoosting

In [25]:
prediction_features(grad_clf, GAME_RESULT, df_train, feature_train_news_features)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    7.3s finished


0.5286451007969996
features importantes
[0.56561741 0.15664484 0.27773774]


### Funções para predição.

In [0]:
def prediction(clf,target, dataFrame):
    
#     features = ['m.odds.f.1x2.f.v.med', 
#                 'm.odds.f.1x2.m.v.med', 
#                 'm.odds.f.1x2.u.v.med', 
#                 'm.odds.s.1x2.h.t.med',
#                 'm.odds.s.1x2.d.t.med',
#                 'm.odds.s.1x2.a.t.med']
    
    features = ['m.odds.s.1x2.h.t.med',
                'm.odds.s.1x2.d.t.med',
                'm.odds.s.1x2.a.t.med']
    

    param_grid = {}
    grid= GridSearchCV(clf, param_grid=param_grid, verbose=1, cv=5)

    grid.fit(dataFrame[features],dataFrame[target])

    print(grid.grid_scores_)
    print(grid.best_score_)

    
def prediction_bestparam(clf,target, dataFrame, param_grid):
    
#     features = ['m.odds.f.1x2.f.v.med', 
#                 'm.odds.f.1x2.m.v.med', 
#                 'm.odds.f.1x2.u.v.med', 
#                 'm.odds.s.1x2.h.t.med',
#                 'm.odds.s.1x2.d.t.med',
#                 'm.odds.s.1x2.a.t.med']

    # features = ['m.odds.s.1x2.h.t.med',
    #             'm.odds.s.1x2.d.t.med',
    #             'm.odds.s.1x2.a.t.med']

    features = [ 
                ML_REAL_PROB_HOME,
                ML_REAL_PROB_DRAW,
                ML_REAL_PROB_AWAY]
    
    grid= GridSearchCV(clf, param_grid=param_grid, verbose=1, cv=5)

    grid.fit(dataFrame[features],dataFrame[target])
    grid.predict_proba(dataFrame[features])

    #print(grid.grid_scores_)
    print(grid.best_score_)
    print(grid.best_params_)
    

## Treinando algoritmos

### * Treinando Adaboost

In [27]:
# ada_clf = AdaBoostClassifier()

ada_param_grid ={'n_estimators': [160], 
             'learning_rate': [0.09],
            'random_state': [1]}

prediction_bestparam(ada_clf, GAME_RESULT, df_train, ada_param_grid)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   11.0s finished


0.5320206282231599
{'learning_rate': 0.09, 'n_estimators': 160, 'random_state': 1}


### * Treinando RandomForest

In [58]:
# rf_clf = RandomForestClassifier()

# rf_param_grid ={'n_estimators': [10], 
#             'max_depth': [2],
#             'min_samples_leaf': [1],
#             'min_weight_fraction_leaf': [0.2],
#             'n_jobs': [1],
#             'random_state': [10],
#             'verbose': [0]}


rf_param_grid ={'n_estimators': list(range(1,11)), 
            'max_depth': [2],
            'min_samples_leaf': [1],
            'min_weight_fraction_leaf': np.arange(0.1, 0.5, 0.1),
            'n_jobs': [1],
            'random_state': [10],
            'verbose': [0]}

prediction_bestparam(rf_clf, GAME_RESULT, df_train, rf_param_grid)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


0.5308954524144398
{'max_depth': 2, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.2, 'n_estimators': 10, 'n_jobs': 1, 'random_state': 10, 'verbose': 0}


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.2s finished


### * Treinando GradientBoosting

In [29]:
# grad_clf = GradientBoostingClassifier()

grad_param_grid ={'loss': ['deviance'], 
            'learning_rate': [0.09],
            'n_estimators': [150],
            'max_depth': [1],
            'min_samples_leaf': [5],
            'verbose': [0],
            'random_state': [1]}

prediction_bestparam(grad_clf, GAME_RESULT, df_train, grad_param_grid)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    7.3s finished


0.5332395686826067
{'learning_rate': 0.09, 'loss': 'deviance', 'max_depth': 1, 'min_samples_leaf': 5, 'n_estimators': 150, 'random_state': 1, 'verbose': 0}


#  Testando os classificadores com o df teste

### Funções e constante para o treino

In [0]:
features = ['m.odds.f.1x2.f.v.med', 
                'm.odds.f.1x2.m.v.med', 
                'm.odds.f.1x2.u.v.med', 
                'm.odds.s.1x2.h.t.med',
                'm.odds.s.1x2.d.t.med',
                'm.odds.s.1x2.a.t.med']

# features = ['m.odds.s.1x2.h.t.med',
#                 'm.odds.s.1x2.d.t.med',
#                 'm.odds.s.1x2.a.t.med']
    

ADABOOST = 'ada'
RANDOMFOREST = 'rf'
GRADIENTBOOST = 'grad'

def validation_predict(clf, param_grid, df_train, df_test, features, target, nome_clf):
    
    print(nome_clf + ': ' + target)
    
    grid= GridSearchCV(clf, param_grid, verbose=1, cv=5)
    grid.fit(df_train[features],df_train[target])

    grid.best_score_
    p = grid.predict(df_test[features])

    new_column = nome_clf+'_'+target+'_predict'
    df_test[new_column] = p

    hits = df_test[df_test[new_column] == df_test[target]]
    print(float(len(hits))/len(df_test))
    return formater_porcent(float(len(hits))/len(df_test))

In [0]:
nome_algotirmo = []
score_alg = []

### * Testando Adaboost

In [32]:
nome_algotirmo.append('Adaboost')
score_alg.append(validation_predict(ada_clf, ada_param_grid, df_train, df_test, features, GAME_RESULT, ADABOOST))


ada: m.res.1x2
Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   12.0s finished


0.5422419460881


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


### * Testando RandomForest

In [33]:
nome_algotirmo.append('RandomForest')
score_alg.append(validation_predict(rf_clf, rf_param_grid, df_train, df_test, features, GAME_RESULT, RANDOMFOREST))


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


rf: m.res.1x2
Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.2s finished


0.5486522024983563


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


### * Testando GradientBoosting

In [34]:
nome_algotirmo.append('GradientBoosting')
score_alg.append(validation_predict(grad_clf, grad_param_grid, df_train, df_test, features, GAME_RESULT, GRADIENTBOOST))


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


grad: m.res.1x2
Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    7.9s finished


0.5438856015779092


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


## Comparando resultado dos algoritmos

In [59]:
import plotly as py
import plotly.graph_objs as go

data = [go.Bar(
            x=nome_algotirmo,
            y=score_alg,
    textposition = 'auto',
        text=score_alg
    )]


layout = go.Layout(
    title='Scores dos Algoritmos',
    yaxis=dict(
        title='Acerto em porcentagem',
        
    )
)

# fig = go.Figure(data=data, layout=layout)
# py.offline.plot(fig, filename='resultado-algoritmos')

/usr/local/lib/python3.6/dist-packages/plotly/offline/offline.py:562: UserWarning:

Your filename `resultado-algoritmos` didn't end with .html. Adding .html to the end of your file.



'resultado-algoritmos.html'